netkit-jh/netkit-jh-build

fs/filesystem-tweaks/usr/lib/systemd/system/getty@.service, fs/packages-list
Changing from mingetty to agetty:
- added `util-linux` to package list (this contains agetty)
- removed `mingetty` from package list as it's no longer needed
- changed command in getty systemd service file to start agetty instead of mingetty
=> Switch from mingetty to agetty

.dockerignore, Dockerfile, docker-start.sh
Originally docker ran a mount command to mount /proc, followed by make. In docker for windows this failed as /proc was already mounted in the container. 
The image now includes a docker-start.sh script which will only attempt to mount /proc if it doesn't already exist. It also checks that you have mounted a directory at /netkit-build and that there is a makefile in that directory. If these fail there are more verbose errors that should help people :)
=> Improving Dockerfile and adding docker script

core/setup_scripts/check_configuration.d/01-check_path.sh, core/setup_scripts/check_configuration.d/02-check_environment.sh, core/setup_scripts/check_configuration.sh
`check_configuration.sh` must be run inside `$NETKIT_HOME/setup_scripts`. The current implementation assumes it is ran inside `$NETKIT_HOME`, so all of the suggested checks and fixes for the `NETKIT_HOME` variable assume it should be the user's current directory, when it should actually be `setup_scripts/../` (`$PWD/..`).
Some issues were addressed in commit e2e83c58a90cc5cf3d08619482cc9b968fe654ec, however only the checks were, not ones in the fixes echo'ed to the user.
Also added is a check that the script is, indeed, running inside `setup_scripts`.
=> Replace $PWD usage in check_configuration scripts

install-netkit-jh.sh
Install script now checks the Netkit configuration. This previously failed in Ubuntu (and related) distributions because sourcing .bashrc in a non-interactive shell was not possible by default. The fix simply evaluates the variables' export statements.
=> Check configuration inside installation script

fs/filesystem-tweaks/etc/netkit/netkit-phase2
As suggested in https://github.com/netkit-jh/netkit-jh-build/issues/51, piping files into /bin/bash will support brace expansion.
This pull request fixes #51.
=> Pipe startup and shutdown files to /bin/bash

install-netkit-jh.sh
* Added `set -e` to ensure the install script does not fail silently. Whenever a command causes an error, the script will now exit. This should aid the Netkit dev team with debugging issues.
* Changed `#!/bin/bash` to `#!/usr/bin/env bash` to ensure the installation script does not assume `bash` is under `/bin`. Now it will check the `$PATH` for `bash`.
=> Improve install script

core/setup_scripts/check_configuration.d/09-check_architecture.sh
Add a new line to the error message on the check architecture script to suggest a reason for the failure to the user.
=> Add glibc warning message inside check_architecture

core/bin/block-wrapper, core/bin/lstart, core/bin/script_utils, core/bin/vcrash, core/bin/vstart, core/man/man1/lstart.1, core/man/man1/vstart.1, core/man/man5/netkit.conf.5, core/netkit.conf, core/setup_scripts/check_configuration.d/07-check_terminal_emulators.sh, core/setup_scripts/handle_config.sh
tmux can now be used as a con0 option - which can be enabled with `VM_CON0=tmux` instead of the old `USE_TMUX=TRUE`
`TMUX_OPEN_TERMS` now uses `yes || no` instead of `TRUE || FALSE`, for consistency with other variables.
This should fix problems with `con0=this`, `con0=none` etc
pls test this and consider a beta release before i end up breaking more stuff
=> Make tmux a con0 option instead of a separate option - `VM_CON0=tmux`

install-netkit-jh.sh
Hosts with multiple shell environments may have source files that fail when sourced under a different shell.
Currently, to enable a successful `./check-configuration.sh` on installation, `.zshrc` and `.bashrc` are sourced if they exist. So if running in Zsh, `source .bashrc` is still ran which may fail with shell-specific commands (and vice versa).
The issue is fixed by just removing it. Line 222 in this PR makes it redundant - the environment variables are exported with the `eval` statement.
=> Prevent `source ./.<shell>rc` failure

core/netkit.conf
Done some testing and there's no disadvantage to increasing the maximum number of machines on parallel startup. It seems to use 100% of your CPU regardless of the number of VMs starting up, and memory usage only increases by the number of machines present. Setting it to `0` may be up for debate though?
=> Increase default `MAX_SIMULTANEOUS_VMS` config var

core/bin/script_utils
This fixes the issue where machines with the name format of:
```
part1
part1<non-word-char>part2
```
causes an issue in `vcrash part1` where the `grep` through the `ps` output would return entries for both machines (since the non-word-char terminates the grep search with `-w`). The process at the top of the list would be killed, which would be the one with the lowest PID (hence could be either machine).
=> fix Issue #77

fs/disabled-services, fs/packages-list
Added ucarp to allow for automatic failover when a device goes down (https://manpages.ubuntu.com/manpages/bionic/man8/ucarp.8.html)
=> added ucarp support

fs/disabled-services, fs/packages-list
ucarp does not have a package on Debian Bullseye repositories yet. This means the package installation in [install-netkit-fs.sh](https://github.com/netkit-jh/netkit-jh-build/blob/9d3d4fe42e5fdebfa6ff0fc043e61f14fa7401ba/fs/install-netkit-fs.sh#L20) fatally fails, resulting in no packages getting installed.
This pull request can be reverted when ucarp gets added to Bullseye.
=> Remove ucarp from installed packages

core/bin/vstart, core/man/man1/vstart.1, core/man/man5/netkit.conf.5, core/netkit.conf, core/setup_scripts/handle_config.sh
`--tmux-attached`/`--tmux-detached` allows usage of tmux alongside configuring its start-up behaviour, however there is no functionality (beyond changing `netkit.conf`) to independently set the primary console whilst using the default (`netkit.conf`) tmux start-up behaviour.
This patch adds `tmux` as a valid primary console option:
```bash
vstart test --con0=tmux
```
=> Allow tmux as a valid con0 option

kernel/Makefile
Building Netkit-JH from source would fail on the kernel download with `cp: cannot stat 'linux-5.13.4.tar.xz': No such file or directory`. This is because the source and destination paths of:
```bash
cp ${KERNEL_ARCHIVE_NAME} ${CACHE_DIR}/${KERNEL_ARCHIVE_NAME}
```
are the wrong around since commit 94fa19b115e0a3a0a0bd7f17d6b715874ef69643.
The `wget` outputs directly to the cache directory now, so the archive must be duplicated into the build directory (not the other way around as per the previous operation).
=> Fix kernel download error from commit 94fa19b115e0a3a0a0bd7f17d6b715874ef69643

core/bin/script_utils, core/bin/vpackage, core/man/man1/vpackage.1, core/netkit.conf, core/setup_scripts/handle_config.sh
This PR adds a vcommand called `vpackage`.
The script mounts the Netkit filesystem image to `/mnt/netkit-fs-mount-point` (default), `chroot`s into the mount point, and then performs a package management command on the filesystem before unmounting it.
Supported subcommands that are passed directly into `apt-get` are:
```
update              synchronise package index files with their respective
sources
upgrade             install latest package versions
dist-upgrade        upgrade and potentially remove unnecessary packages
install PACKAGE...  install or upgrade packages and their dependencies
remove PACKAGE...   remove packages, leaving their configuration files
purge PACKAGE...    remove packages and their configuration files
clean               clear out the apt cache
autoremove …
```
=> Add package installer script (vpackage)

fs/packages-list
StrongSwan needs a HTTP fetcher plugin (`curl` or `soup`) to do OCSP requests. Neither are provided by default but `libstrongswan-extra-plugins` provides `curl`.
=> Add libstrongswan-extra-plugins

core/bash-completion/helpers, core/bin/vcommon
Patch for version 2.0.0-beta.
Current commands use longopts over shortopts for readability. As identified by @Oshawk, this presents an issue with `awk` where GNU awk is not commonly installed by default (mawk is used by default in Ubuntu). Using shortopts (`-v` and `-F`) is a more portable alternative.
=> Use portable `awk` options

install-netkit-jh.sh
Favour shortopts over longopts for the `cut` command.
=> 2.0.0-beta hotfix: use portable `cut` shortopts

install-netkit-jh.sh
Unset the `file` variable used to load completion scripts in `.bashrc`. Without this, every shell session will have a global `file` variable set to the vstart completion script path.
=> Unset global file variable after usage in .bashrc

install-netkit-jh.sh
When an old install is backed up, the target directory for the current install is not created.
This patch fixes that by creating the install directory regardless of an old install existing or not.
=> Create install directory if old install was backed up

install-netkit-jh.sh
Add `jq` as a dependency in the install script. The package is used in the version check for parsing GitHub's API response.
=> Add jq as a dependency

core/bin/lstart
Warn if a lab.conf value has trailing whitespace, which could be hard to manually detect.
The reason for not automatically stripping whitespace to avoid ambiguity, making assumptions for other input parsing, and because there is no mechanism for escaping whitespace if it is required.
=> Check for trailing whitespace in lab.conf

core/bin/lstart, core/bin/vstart
When running `lstart`, only warn if a machine cannot be started (such as if it is already running or has invalid parameters).
Originally, the error was fatal, which prevented the following valid operation:
```bash
$ ls
a    a.startup    b    b.startup    lab.conf    lab.dep    r    r.startup
$ lstart
$ lcrash a b
$ lstart
```
=> Ignore machines unable to start in lstart

core/bin/lstart, core/bin/script_utils
The previous Makefile for parallel startup required passing to Make via stdin (the `--file` argument would not work). This causes issues with `block-wrapper` when user input is expected.
The on-the-fly Makefile is now created with an explicit recipe for each host. In addition, every host is made a "phony" target to prevent conflict with identically named files.
=> Use a more reliable Makefile for parallel lstart

core/bash-completion/completions/vconnect, core/bin/block-wrapper, core/bin/lstart, core/bin/vclean, core/bin/vconnect, core/bin/vstart, core/man/man1/vconnect.1
`vclean --kill-machines` now kills the 'netkit' tmux server. This is only possible for the server owned by the current user so a warning has been added where appropriate (using `su` to get around this would cause inconsistency with other Netkit commands that perform operations on behalf of other users).
`vconnect` now has a `-k`/`--kill` and `--kill-all` option for terminating tmux sessions per-machine.
If a tmux session for a machine already exists, `vstart` will now fail (behaviour in accordance with other conflicts). The original method of prompting the user for permission to kill the session did not work when `vstart` was ran in the background (i.e., when used with `lstart`).
The lack of Bash completion for lstart/ltest's `--tmux-attached`/`--tmux-detached` options has also been …
=> Kill tmux sessions with `vclean`

core/bin/lcommon
.log files are not created in the lab directories, they were an artefact of the original Netkit project. It is redundant to try and remove them when cleaning labs.
=> Ignore log files when cleaning labs

core/bash-completion/completions/vcrash, core/bin/lcommon, core/bin/vcrash, core/man/man1/lcrash.1, core/man/man1/vcrash.1
vcrash now deletes the COW filesystem by default and has a `--keep-fs` option to avoid this behaviour (replacing `--remove-fs`). This is in line with lcrash.
As mentioned in Issue #109, vhalt/lhalt are the opposite and will *keep* the fs by default, and have a `--remove-fs` option to delete it.
=> Change vcrash to delete fs by default (fix issue #109)

core/bin/vcommon, core/man/man5/netkit.conf.5, core/netkit.conf.default
Like `LOGFILENAME`, give the ability to disable the virtual hub log by setting the `HUB_LOG` configuration variable to the empty string. This fixes Issue #111.
This patch also makes the timestamp update for each log message by updating it dynamically with `strftime()` - the original solution set a static timestamp when the command was invoked. The extra padding around fields in the log has also been removed, since it was redundant.
=> Disable hub log if HUB_LOG is empty string (fix issue #111)

core/bin/vdump, core/man/man1/vdump.1
`vdump --verbose` messages now go to standard error to avoid mixing up with the packet dump output stream. This patch remediates Issue #110.
=> Redirect `vdump --verbose` to stderr (fix Issue #110)

core/bin/vcommon, core/bin/vlist, core/man/man1/vlist.1
Short patch to make vlist display the memory unit (KB) in its column label, otherwise the unit is ambiguous and has to be inferred from other contexts.
=> Show KB unit in vlist memory column

core/bash-completion/completions/vstart, core/bin/block-wrapper, core/bin/vconnect, core/bin/vstart, core/man/man1/vstart.1, core/man/man5/netkit.conf.5, core/netkit.conf.default, core/setup_scripts/change_terminal.sh, core/setup_scripts/check_configuration.d/7_check_terminal_emulators.sh, tests/configs/35-wsl
With the advent of Windows 11, Microsoft have now made Windows Terminal the default emulator application on Windows. The user can change the default back to the Windows Console Host (conhost.exe).
Using `--xterm=wsl` with vstart will launch VMs by invoking cmd.exe. This will cause Windows to use the *default* terminal emulator--**not always** (as documented in Netkit-JH) ConHost. This presents the following issue: if the system default is Windows Terminal, Netkit-JH will launch the VM in Windows Terminal with the "wsl" option; this makes `--xterm=wsl` and `--xterm=wt` practically equivalent.
This patch changes the "wsl" option so ConHost is *always* used (by invoking `conhost.exe` directly). Therefore, regardless of the system's default terminal emulator, the user can always choose with …
=> Always use conhost.exe with the "wsl" xterm option (+ rename the option to "conhost")

core/bin/lhalt
As per the documentation, `-r`/`--remove-fs` cannot be used in conjunction with `-q`/`--quick` for either lhalt or vhalt.
The CLI parsing for lhalt has a bug where it will instead error when `--remove-fs` is **not** used with `--quick`.
This patch just flips one of the test conditions.
=> Bugfix where lhalt -r couldn't be used *without* -q

fs/disabled-services
Stop the bird and bird6 services from auto-starting on boot.
=> Disable bird and bird6 services

core/bin/linfo, core/bin/vcommon
In the rare cases where machines, collision domains, or options/values have DOT language or XML special characters in them, GraphViz will produce unexpected results when generating a lab map with `linfo --map`. This patch fixes this behaviour by sufficiently escaping the characters. This fixes Issue #73.
Since all substituted identifiers are quoted, the only DOT language metacharacter that must be escaped is the double quote:
`"` -> `\"`
All of the XML substitutions are text content, so just require the usual 5 metacharacters escaped:
`&` -> `&amp;`
`>` -> `&gt;`
`<` -> `&lt;`
`"` -> `&quot;`
`'` -> `&apos;`
=> Escape DOT and XML metacharacters in linfo mapping (fixes Issue #73)

core/setup_scripts/check_configuration.d/4_check_manpath.sh, install-netkit-jh.sh
Two quick bug fixes in this patch:
1. The install script now ignores if the old Netkit-JH directory does not have a *netkit.conf* file (with a warning).
2. The man page check configuration script will use the netkit-jh(7) manual, not netkit(7).
=> Install process bugfixes

core/bin/manage_tuntap
On some distributions, the iptables utility with the **--check** option shows the matched rule on stdout, which negatively affects the manage_tuntap output formatting.
This quick patch remedies that by redirecting the stdout to */dev/null*.
=> Hide `iptables --check` output

install-netkit-jh.sh
Debian and some other distros do not have man-db installed by default.
=> Add man-db as install dependency

core/man/man5/lab.conf.5, fs/filesystem-tweaks/usr/lib/systemd/system/netkit-shutdown.service, fs/filesystem-tweaks/usr/lib/systemd/system/netkit-startup-phase1.service, fs/filesystem-tweaks/usr/lib/systemd/system/netkit-startup-phase2.service
Set the `WorkingDirectory` directive of the Netkit-JH startup and shutdown services to */root*, since some users write scripts assuming it (which is the correct assumption, this is just to make it explicit).
=> Explicitly set startup service CWD to /root

core/bin/lstart
Netkit-JH will now warn if an update-check fails (e.g., lack of Internet access or lack of `jq`|`curl` installed). It will also now try the GitHub update check if the *.latest-X-version* file(s) could not be read, irrespective of the user's update-check due-date.
=> Handle failed update checks

README.mdown
`make install` runs the installation script with the `--no-packages` option, which means users building Netkit-JH from source may not have all required dependencies to run Netkit-JH as expected.
=> List dependencies to install when building from source
